drop table if exists chat CASCADE;
CREATE TABLE chat (
    ID SERIAL,
    USERNAME VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(255) NOT NULL,
    ROOMNUMBER INT NOT NULL,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (ID)
);
